### ISSUE TITLE
Wrong definition of golden ratio?

### ISSUE THREAD

**Issue by filtron** [nathanaelbosch/TuePlots.jl#13]
Package defines golden ratio as 

```julia
const GOLDEN_RATIO = (5.0^0.5 - 1.0) / 2.0
```

but [wikipedia](https://en.wikipedia.org/wiki/Golden_ratio) says 
```math 
\varphi = \frac{ \sqrt{5} + 1}{2},
```

i.e., sign error?

**Comment by nathanaelbosch** [comment]
You're right, it's not quite the "golden ratio" as defined there. Basically, we wannt $\text{width} / \text{height} = \varphi$. But we typically want to compute the height for a given width, i.e. $\text{height} = \text{width} / \varphi$. The `GOLDEN_RATIO` used in the package corresponds to $1 / \varphi$. Then `height = width * GOLDEN_RATIO`. So this is not a bug, just a not-completely-accurate variable name. If you think things should be different, feel free to make a PR! :)
